class InsertStateData < ActiveRecord::Migration
  def self.up
	State.create(:abbreviation => 'AK', :name => 'Alaska')
	State.create(:abbreviation => 'AZ', :name => 'Arizona')
	State.create(:abbreviation => 'AR', :name => 'Arkansas')
	State.create(:abbreviation => 'CA', :name => 'California')
	State.create(:abbreviation => 'CO', :name => 'Colorado')
	State.create(:abbreviation => 'CT', :name => 'Connecticut')
	State.create(:abbreviation => 'DE', :name => 'Delaware')
	State.create(:abbreviation => 'DC', :name => 'District of Col')
	State.create(:abbreviation => 'FL', :name => 'Florida')
	State.create(:abbreviation => 'GA', :name => 'Georgia')
	State.create(:abbreviation => 'HI', :name => 'Hawaii')
	State.create(:abbreviation => 'ID', :name => 'Idaho')
	State.create(:abbreviation => 'IL', :name => 'Illinois')
	State.create(:abbreviation => 'IN', :name => 'Indiana')
	State.create(:abbreviation => 'IA', :name => 'Iowa')
	State.create(:abbreviation => 'KS', :name => 'Kansas')
	State.create(:abbreviation => 'KY', :name => 'Kentucky')
	State.create(:abbreviation => 'LA', :name => 'Louisiana')
	State.create(:abbreviation => 'ME', :name => 'Maine')
	State.create(:abbreviation => 'MD', :name => 'Maryland')
	State.create(:abbreviation => 'MA', :name => 'Massachusetts')
	State.create(:abbreviation => 'MI', :name => 'Michigan')
	State.create(:abbreviation => 'MN', :name => 'Minnesota')
	State.create(:abbreviation => 'MS', :name => 'Mississippi')
	State.create(:abbreviation => 'MO', :name => 'Missouri')
	State.create(:abbreviation => 'MT', :name => 'Montana')
	State.create(:abbreviation => 'NE', :name => 'Nebraska')
	State.create(:abbreviation => 'NV', :name => 'Nevada')
	State.create(:abbreviation => 'NH', :name => 'New Hampshire')
	State.create(:abbreviation => 'NJ', :name => 'New Jersey')
	State.create(:abbreviation => 'NM', :name => 'New Mexico')
	State.create(:abbreviation => 'NY', :name => 'New York')
	State.create(:abbreviation => 'NC', :name => 'North Carolina')
	State.create(:abbreviation => 'ND', :name => 'North Dakota')
	State.create(:abbreviation => 'OH', :name => 'Ohio')
	State.create(:abbreviation => 'OK', :name => 'Oklahoma')
	State.create(:abbreviation => 'OR', :name => 'Oregon')
	State.create(:abbreviation => 'PA', :name => 'Pennsylvania')
	State.create(:abbreviation => 'RI', :name => 'Rhode Island')
	State.create(:abbreviation => 'SC', :name => 'South Carolina')
	State.create(:abbreviation => 'SD', :name => 'South Dakota')
	State.create(:abbreviation => 'TN', :name => 'Tennessee')
	State.create(:abbreviation => 'TX', :name => 'Texas')
	State.create(:abbreviation => 'UT', :name => 'Utah')
	State.create(:abbreviation => 'VT', :name => 'Vermont')
	State.create(:abbreviation => 'VA', :name => 'Virginia')
	State.create(:abbreviation => 'WA', :name => 'Washington')
	State.create(:abbreviation => 'WV', :name => 'West Virginia')
	State.create(:abbreviation => 'WI', :name => 'Wisconsin')
	State.create(:abbreviation => 'WY', :name => 'Wyoming')
	State.create(:abbreviation => 'AS', :name => 'American Samoa')
	State.create(:abbreviation => 'FM', :name => 'Federated State')
	State.create(:abbreviation => 'GU', :name => 'Guam')
	State.create(:abbreviation => 'MH', :name => 'Marshall Island')
	State.create(:abbreviation => 'MP', :name => 'Northern Marian')
	State.create(:abbreviation => 'PW', :name => 'Palau')
	State.create(:abbreviation => 'PR', :name => 'Puerto Rico')
	State.create(:abbreviation => 'UM', :name => 'U.S. Minor Outl')
	State.create(:abbreviation => 'VI', :name => 'Virgin Islands ')
end

  def self.down
	  State.delete_all
  end
end
