class InsertCorporations < ActiveRecord::Migration
  def self.up
	   Corporation.create(:name => "Exxon Mobil", :logo_path => "ExxonMobil.png")
		Corporation.create(:name => "Wal-Mart Stores", :logo_path => "Wal-Mart.png")
		Corporation.create(:name => "Chevron", :logo_path => "Chevron.png")
		Corporation.create(:name => "ConocoPhillips", :logo_path => "ConocoPhillips.png")
		Corporation.create(:name => "General Electric", :logo_path => "GeneralElectric.png")
		Corporation.create(:name => "General Motors", :logo_path => "GeneralMotors.png")
		Corporation.create(:name => "Ford Motor", :logo_path => "FordMotor.png")
		Corporation.create(:name => "AT&T", :logo_path => "ATT.png")
		Corporation.create(:name => "Hewlett-Packard", :logo_path => "HewlettPackard.png")
		Corporation.create(:name => "Valero Energy", :logo_path => "Valero.png")
		Corporation.create(:name => "Bank of America Corp.", :logo_path => "BankOfAmerica.png")
		Corporation.create(:name => "Citigroup", :logo_path => "Citigroup.png")
		Corporation.create(:name => "Berkshire Hathaway")
		Corporation.create(:name => "International Business Machines")
		Corporation.create(:name => "McKesson")
		Corporation.create(:name => "J.P. Morgan Chase & Co.")
		Corporation.create(:name => "Verizon Communications")
		Corporation.create(:name => "Cardinal Health")
		Corporation.create(:name => "CVS Caremark")
		Corporation.create(:name => "Procter & Gamble")
		Corporation.create(:name => "UnitedHealth Group")
		Corporation.create(:name => "Kroger")
		Corporation.create(:name => "Marathon Oil")
		Corporation.create(:name => "Costco Wholesale")
		Corporation.create(:name => "Home Depot")
		Corporation.create(:name => "AmerisourceBergen", :logo_path => "AmerisourceBergen.png")
		Corporation.create(:name => "Archer Daniels Midland", :logo_path => "ADM.png")
		Corporation.create(:name => "Target")
		Corporation.create(:name => "Johnson & Johnson")
		Corporation.create(:name => "Morgan Stanley")
		Corporation.create(:name => "State Farm Insurance Cos.")
		Corporation.create(:name => "WellPoint")
		Corporation.create(:name => "Dell")
		Corporation.create(:name => "Boeing")
		Corporation.create(:name => "Microsoft")
		Corporation.create(:name => "Walgreen")
		Corporation.create(:name => "United Technologies")
		Corporation.create(:name => "Dow Chemical")
		Corporation.create(:name => "MetLife")
		Corporation.create(:name => "Goldman Sachs Group")
		Corporation.create(:name => "Sunoco")
		Corporation.create(:name => "Wells Fargo")
		Corporation.create(:name => "United Parcel Service")
		Corporation.create(:name => "Caterpillar")
		Corporation.create(:name => "Medco Health Solutions")
		Corporation.create(:name => "Pfizer")
		Corporation.create(:name => "Lowe's")
		Corporation.create(:name => "Time Warner")
		Corporation.create(:name => "Sears Holdings")
		Corporation.create(:name => "Safeway")
		Corporation.create(:name => "Supervalu")
		Corporation.create(:name => "PepsiCo")
		Corporation.create(:name => "Kraft Foods")
		Corporation.create(:name => "Lockheed Martin")
		Corporation.create(:name => "Hess")
		Corporation.create(:name => "Best Buy")
		Corporation.create(:name => "Cisco Systems")
		Corporation.create(:name => "Johnson Controls")
		Corporation.create(:name => "FedEx")
		Corporation.create(:name => "Walt Disney")
		Corporation.create(:name => "Intel")
		Corporation.create(:name => "Sysco")
		Corporation.create(:name => "Honeywell International")
		Corporation.create(:name => "Sprint Nextel")
		Corporation.create(:name => "Enterprise GP Holdings")
		Corporation.create(:name => "GMAC")
		Corporation.create(:name => "Ingram Micro", :logo_path => "IngramMicro.png")
		Corporation.create(:name => "Comcast")
		Corporation.create(:name => "Northrop Grumman")
		Corporation.create(:name => "News Corp.")
		Corporation.create(:name => "Apple")
		Corporation.create(:name => "CHS")
		Corporation.create(:name => "Coca-Cola")
		Corporation.create(:name => "American Express", :logo_path => "AmericanExpress.png")
		Corporation.create(:name => "DuPont")
		Corporation.create(:name => "New York Life Insurance")
		Corporation.create(:name => "Aetna", :logo_path => "Aetna.png")
		Corporation.create(:name => "Motorola")
		Corporation.create(:name => "Plains All American Pipeline")
		Corporation.create(:name => "Abbott Laboratories", :logo_path => "AbbottLaboratories.png")
		Corporation.create(:name => "Allstate", :logo_path => "Allstate.png")
		Corporation.create(:name => "TIAA-CREF")
		Corporation.create(:name => "General Dynamics")
		Corporation.create(:name => "Prudential Financial")
		Corporation.create(:name => "Humana")
		Corporation.create(:name => "Liberty Mutual Insurance Group")
		Corporation.create(:name => "Deere")
		Corporation.create(:name => "HCA")
		Corporation.create(:name => "Tyson Foods")
		Corporation.create(:name => "Alcoa", :logo_path => "Alcoa.png")
		Corporation.create(:name => "Tesoro")
		Corporation.create(:name => "Murphy Oil")
		Corporation.create(:name => "Philip Morris International")
		Corporation.create(:name => "Emerson Electric")
		Corporation.create(:name => "3M", :logo_path => "3M.png")
		Corporation.create(:name => "Macy's")
		Corporation.create(:name => "International Paper")
		Corporation.create(:name => "Occidental Petroleum")
		Corporation.create(:name => "Travelers Cos.")
		Corporation.create(:name => "Rite Aid")
		Corporation.create(:name => "Publix Super Markets")
		Corporation.create(:name => "Tech Data")
		Corporation.create(:name => "Merck")
		Corporation.create(:name => "AMR", :logo_path => "AMR.png")
		Corporation.create(:name => "United States Steel")
		Corporation.create(:name => "Nucor")
		Corporation.create(:name => "McDonald's")
		Corporation.create(:name => "Raytheon")
		Corporation.create(:name => "Staples")
		Corporation.create(:name => "Wyeth")
		Corporation.create(:name => "Delta Air Lines")
		Corporation.create(:name => "Fannie Mae")
		Corporation.create(:name => "Oracle")
		Corporation.create(:name => "Fluor")
		Corporation.create(:name => "Express Scripts")
		Corporation.create(:name => "Coca-Cola Enterprises")
		Corporation.create(:name => "Google")
		Corporation.create(:name => "Northwestern Mutual")
		Corporation.create(:name => "Manpower")
		Corporation.create(:name => "Bristol-Myers Squibb")
		Corporation.create(:name => "Delphi")
		Corporation.create(:name => "Eli Lilly")
		Corporation.create(:name => "UAL")
		Corporation.create(:name => "Nationwide")
		Corporation.create(:name => "Constellation Energy")
		Corporation.create(:name => "DirecTV Group")
		Corporation.create(:name => "Goodyear Tire & Rubber")
		Corporation.create(:name => "Kimberly-Clark")
		Corporation.create(:name => "U.S. Bancorp")
		Corporation.create(:name => "Amazon.com", :logo_path => "Amazon.com.png")
		Corporation.create(:name => "TJX")
		Corporation.create(:name => "Cigna")
		Corporation.create(:name => "Whirlpool")
		Corporation.create(:name => "Exelon")
		Corporation.create(:name => "Massachusetts Mutual Life Insurance")
		Corporation.create(:name => "Nike")
		Corporation.create(:name => "World Fuel Services")
		Corporation.create(:name => "Schering-Plough")
		Corporation.create(:name => "J.C. Penney")
		Corporation.create(:name => "International Assets Holding")
		Corporation.create(:name => "Halliburton")
		Corporation.create(:name => "Burlington Northern Santa Fe")
		Corporation.create(:name => "Union Pacific")
		Corporation.create(:name => "Avnet")
		Corporation.create(:name => "Capital One Financial")
		Corporation.create(:name => "Freeport-McMoRan Copper & Gold")
		Corporation.create(:name => "Xerox")
		Corporation.create(:name => "Illinois Tool Works")
		Corporation.create(:name => "Southern")
		Corporation.create(:name => "Merrill Lynch")
		Corporation.create(:name => "Arrow Electronics")
		Corporation.create(:name => "AFLAC", :logo_path => "Aflac.png")
		Corporation.create(:name => "Computer Sciences")
		Corporation.create(:name => "FPL Group")
		Corporation.create(:name => "Kohl's")
		Corporation.create(:name => "Bank of New York Mellon Corp.")
		Corporation.create(:name => "Dominion Resources")
		Corporation.create(:name => "AES", :logo_path => "AES.png")
		Corporation.create(:name => "Oneok")
		Corporation.create(:name => "Altria Group", :logo_path => "Altria.png")
		Corporation.create(:name => "PPG Industries")
		Corporation.create(:name => "Anadarko Petroleum", :logo_path => "AnadarkoPetroleum.png")
		Corporation.create(:name => "Devon Energy")
		Corporation.create(:name => "Eaton")
		Corporation.create(:name => "Health Net")
		Corporation.create(:name => "Colgate-Palmolive")
		Corporation.create(:name => "Continental Airlines")
		Corporation.create(:name => "Amgen", :logo_path => "Amgen.png")
		Corporation.create(:name => "TRW Automotive Holdings")
		Corporation.create(:name => "Paccar")
		Corporation.create(:name => "L-3 Communications")
		Corporation.create(:name => "EMC")
		Corporation.create(:name => "Textron")
		Corporation.create(:name => "Loews")
		Corporation.create(:name => "Navistar International")
		Corporation.create(:name => "PG&E Corp.")
		Corporation.create(:name => "Viacom")
		Corporation.create(:name => "Gap")
		Corporation.create(:name => "Office Depot")
		Corporation.create(:name => "American Electric Power", :logo_path => "AEP.png")
		Corporation.create(:name => "Cummins")
		Corporation.create(:name => "AutoNation")
		Corporation.create(:name => "Smithfield Foods")
		Corporation.create(:name => "Edison International")
		Corporation.create(:name => "Integrys Energy Group")
		Corporation.create(:name => "CBS")
		Corporation.create(:name => "Sun Microsystems")
		Corporation.create(:name => "ConAgra Foods")
		Corporation.create(:name => "Pepsi Bottling")
		Corporation.create(:name => "Public Service Enterprise Group")
		Corporation.create(:name => "Consolidated Edison")
		Corporation.create(:name => "Toys 'R' Us")
		Corporation.create(:name => "General Mills")
		Corporation.create(:name => "FirstEnergy")
		Corporation.create(:name => "Lear")
		Corporation.create(:name => "Medtronic")
		Corporation.create(:name => "Qwest Communications")
		Corporation.create(:name => "Aramark")
		Corporation.create(:name => "Sara Lee")
		Corporation.create(:name => "National Oilwell Varco")
		Corporation.create(:name => "Waste Management")
		Corporation.create(:name => "Omnicom Group")
		Corporation.create(:name => "Chubb")
		Corporation.create(:name => "Duke Energy")
		Corporation.create(:name => "Entergy")
		Corporation.create(:name => "State Street Corp.")
		Corporation.create(:name => "United Services Automobile Association")
		Corporation.create(:name => "Marriott International")
		Corporation.create(:name => "Progressive")
		Corporation.create(:name => "Kellogg")
		Corporation.create(:name => "SunTrust Banks")
		Corporation.create(:name => "Jabil Circuit")
		Corporation.create(:name => "Danaher")
		Corporation.create(:name => "Reliant Energy")
		Corporation.create(:name => "Texas Instruments")
		Corporation.create(:name => "Dean Foods")
		Corporation.create(:name => "Apache")
		Corporation.create(:name => "Williams")
		Corporation.create(:name => "Baxter International")
		Corporation.create(:name => "Freddie Mac")
		Corporation.create(:name => "Parker Hannifin")
		Corporation.create(:name => "US Airways Group")
		Corporation.create(:name => "Knight")
		Corporation.create(:name => "Land O'Lakes")
		Corporation.create(:name => "Penske Automotive Group")
		Corporation.create(:name => "Coventry Health Care")
		Corporation.create(:name => "Baker Hughes")
		Corporation.create(:name => "Circuit City Stores")
		Corporation.create(:name => "ITT")
		Corporation.create(:name => "Chesapeake Energy")
		Corporation.create(:name => "DISH Network")
		Corporation.create(:name => "Marsh & McLennan")
		Corporation.create(:name => "R.R. Donnelley & Sons")
		Corporation.create(:name => "KBR")
		Corporation.create(:name => "Monsanto")
		Corporation.create(:name => "Weyerhaeuser")
		Corporation.create(:name => "Energy Future Holdings")
		Corporation.create(:name => "CenterPoint Energy")
		Corporation.create(:name => "Yum Brands", :logo_path => "Yum.png")
		Corporation.create(:name => "CSX")
		Corporation.create(:name => "Jacobs Engineering Group")
		Corporation.create(:name => "Xcel Energy")
		Corporation.create(:name => "Community Health Systems")
		Corporation.create(:name => "Qualcomm")
		Corporation.create(:name => "American International Group", :logo_path => "AIG.png")
		Corporation.create(:name => "Southwest Airlines")
		Corporation.create(:name => "Genuine Parts")
		Corporation.create(:name => "Air Products & Chemicals", :logo_path => "AirProducts.png")
		Corporation.create(:name => "Praxair")
		Corporation.create(:name => "Smith International")
		Corporation.create(:name => "Commercial Metals")
		Corporation.create(:name => "Sempra Energy")
		Corporation.create(:name => "Western Refining")
		Corporation.create(:name => "Pepco Holdings")
		Corporation.create(:name => "Avon Products")
		Corporation.create(:name => "Norfolk Southern")
		Corporation.create(:name => "Liberty Global")
		Corporation.create(:name => "Thermo Fisher Scientific")
		Corporation.create(:name => "Dollar General")
		Corporation.create(:name => "BB&T Corp.")
		Corporation.create(:name => "Starbucks")
		Corporation.create(:name => "Huntsman")
		Corporation.create(:name => "Harrah's Entertainment")
		Corporation.create(:name => "URS")
		Corporation.create(:name => "Liberty Media")
		Corporation.create(:name => "SAIC")
		Corporation.create(:name => "H.J. Heinz")
		Corporation.create(:name => "Enbridge Energy Partners")
		Corporation.create(:name => "BJ's Wholesale Club")
		Corporation.create(:name => "Unum Group")
		Corporation.create(:name => "Genworth Financial")
		Corporation.create(:name => "Calpine")
		Corporation.create(:name => "Principal Financial")
		Corporation.create(:name => "Lincoln National")
		Corporation.create(:name => "Terex")
		Corporation.create(:name => "Mosaic")
		Corporation.create(:name => "Masco")
		Corporation.create(:name => "PNC Financial Services Group")
		Corporation.create(:name => "Guardian Life Ins. Co. of America")
		Corporation.create(:name => "Regions Financial")
		Corporation.create(:name => "Rohm & Haas")
		Corporation.create(:name => "Visteon")
		Corporation.create(:name => "Tenet Healthcare")
		Corporation.create(:name => "Eastman Kodak")
		Corporation.create(:name => "DTE Energy")
		Corporation.create(:name => "Energy Transfer Equity")
		Corporation.create(:name => "Hartford Financial Services")
		Corporation.create(:name => "Progress Energy")
		Corporation.create(:name => "NiSource")
		Corporation.create(:name => "Limited Brands")
		Corporation.create(:name => "Global Partners")
		Corporation.create(:name => "Sanmina-SCI")
		Corporation.create(:name => "YRC Worldwide")
		Corporation.create(:name => "Reynolds American")
		Corporation.create(:name => "First Data")
		Corporation.create(:name => "GameStop")
		Corporation.create(:name => "Automatic Data Processing")
		Corporation.create(:name => "Reliance Steel & Aluminum")
		Corporation.create(:name => "Assurant")
		Corporation.create(:name => "C.H. Robinson Worldwide")
		Corporation.create(:name => "Nordstrom")
		Corporation.create(:name => "Fifth Third Bancorp")
		Corporation.create(:name => "eBay")
		Corporation.create(:name => "Pilgrim's Pride")
		Corporation.create(:name => "Hertz Global Holdings")
		Corporation.create(:name => "AGCO", :logo_path => "Agco.png")
		Corporation.create(:name => "Aon")
		Corporation.create(:name => "Centex")
		Corporation.create(:name => "Campbell Soup")
		Corporation.create(:name => "Ashland")
		Corporation.create(:name => "CarMax")
		Corporation.create(:name => "Crown Holdings")
		Corporation.create(:name => "OfficeMax")
		Corporation.create(:name => "PPL")
		Corporation.create(:name => "Applied Materials")
		Corporation.create(:name => "Dana Holding")
		Corporation.create(:name => "Pantry")
		Corporation.create(:name => "Steel Dynamics")
		Corporation.create(:name => "Western Digital")
		Corporation.create(:name => "Boston Scientific")
		Corporation.create(:name => "Peter Kiewit Sons'")
		Corporation.create(:name => "Sherwin-Williams")
		Corporation.create(:name => "Targa Resources")
		Corporation.create(:name => "Whole Foods Market")
		Corporation.create(:name => "Este Lauder")
		Corporation.create(:name => "Owens-Illinois")
		Corporation.create(:name => "Ameren", :logo_path => "Ameren.png")
		Corporation.create(:name => "Synnex")
		Corporation.create(:name => "Dole Food")
		Corporation.create(:name => "XTO Energy")
		Corporation.create(:name => "SLM")
		Corporation.create(:name => "TravelCenters of America")
		Corporation.create(:name => "Dover")
		Corporation.create(:name => "AK Steel Holding", :logo_path => "AK_Steel.png")
		Corporation.create(:name => "VF")
		Corporation.create(:name => "Ball")
		Corporation.create(:name => "Sonic Automotive")
		Corporation.create(:name => "Virgin Media")
		Corporation.create(:name => "Owens & Minor")
		Corporation.create(:name => "Winn-Dixie Stores")
		Corporation.create(:name => "Quest Diagnostics")
		Corporation.create(:name => "Cablevision Systems")
		Corporation.create(:name => "Atmos Energy")
		Corporation.create(:name => "MGM Mirage")
		Corporation.create(:name => "Yahoo")
		Corporation.create(:name => "ArvinMeritor")
		Corporation.create(:name => "Becton Dickinson")
		Corporation.create(:name => "Ameriprise Financial", :logo_path => "Ameriprise.png")
		Corporation.create(:name => "Oshkosh")
		Corporation.create(:name => "EOG Resources")
		Corporation.create(:name => "Fortune Brands")
		Corporation.create(:name => "Discover Financial Services")
		Corporation.create(:name => "Peabody Energy")
		Corporation.create(:name => "Goodrich")
		Corporation.create(:name => "Bed Bath & Beyond")
		Corporation.create(:name => "Smurfit-Stone Container")
		Corporation.create(:name => "Shaw Group")
		Corporation.create(:name => "Dillard's")
		Corporation.create(:name => "Family Dollar Stores")
		Corporation.create(:name => "Great Atlantic & Pacific Tea")
		Corporation.create(:name => "Interpublic Group")
		Corporation.create(:name => "Precision Castparts")
		Corporation.create(:name => "NRG Energy")
		Corporation.create(:name => "Eastman Chemical")
		Corporation.create(:name => "MeadWestvaco")
		Corporation.create(:name => "W.W. Grainger")
		Corporation.create(:name => "Mohawk Industries")
		Corporation.create(:name => "Celanese")
		Corporation.create(:name => "CMS Energy")
		Corporation.create(:name => "Emcor Group")
		Corporation.create(:name => "Gannett")
		Corporation.create(:name => "CC Media Holdings")
		Corporation.create(:name => "Hormel Foods")
		Corporation.create(:name => "Darden Restaurants")
		Corporation.create(:name => "Stryker")
		Corporation.create(:name => "Avery Dennison")
		Corporation.create(:name => "UGI")
		Corporation.create(:name => "D.R. Horton")
		Corporation.create(:name => "AbitibiBowater", :logo_path => "AbitibiBowater.png")
		Corporation.create(:name => "AutoZone")
		Corporation.create(:name => "WellCare Health Plans")
		Corporation.create(:name => "KeyCorp")
		Corporation.create(:name => "Frontier Oil")
		Corporation.create(:name => "Ross Stores")
		Corporation.create(:name => "Charter Communications")
		Corporation.create(:name => "Autoliv")
		Corporation.create(:name => "Newell Rubbermaid")
		Corporation.create(:name => "American Family Insurance Group", :logo_path => "AmericanFamilyInsurance.png")
		Corporation.create(:name => "Henry Schein")
		Corporation.create(:name => "Domtar")
		Corporation.create(:name => "McGraw-Hill")
		Corporation.create(:name => "Omnicare")
		Corporation.create(:name => "Pulte Homes")
		Corporation.create(:name => "Visa")
		Corporation.create(:name => "Pitney Bowes")
		Corporation.create(:name => "General Cable")
		Corporation.create(:name => "CIT Group")
		Corporation.create(:name => "First American Corp.")
		Corporation.create(:name => "Ryder System")
		Corporation.create(:name => "Newmont Mining")
		Corporation.create(:name => "Affiliated Computer Services", :logo_path => "ACS.png")
		Corporation.create(:name => "SPX")
		Corporation.create(:name => "Ecolab")
		Corporation.create(:name => "Anixter International")
		Corporation.create(:name => "Embarq")
		Corporation.create(:name => "Wesco International")
		Corporation.create(:name => "Hexion Specialty Chemicals")
		Corporation.create(:name => "Black & Decker")
		Corporation.create(:name => "Thrivent Financial for Lutherans")
		Corporation.create(:name => "Franklin Resources")
		Corporation.create(:name => "Avis Budget Group")
		Corporation.create(:name => "Harley-Davidson")
		Corporation.create(:name => "Aleris International", :logo_path => "Aleris.png")
		Corporation.create(:name => "Corning")
		Corporation.create(:name => "Mattel")
		Corporation.create(:name => "Tenneco")
		Corporation.create(:name => "Starwood Hotels & Resorts")
		Corporation.create(:name => "Advanced Micro Devices", :logo_path => "AMD.png")
		Corporation.create(:name => "Symantec")
		Corporation.create(:name => "Holly")
		Corporation.create(:name => "Cameron International")
		Corporation.create(:name => "Owens Corning")
		Corporation.create(:name => "Micron Technology")
		Corporation.create(:name => "Northeast Utilities")
		Corporation.create(:name => "Agilent Technologies", :logo_path => "Agilent.png")
		Corporation.create(:name => "ProLogis")
		Corporation.create(:name => "Dr Pepper Snapple Group")
		Corporation.create(:name => "Group 1 Automotive")
		Corporation.create(:name => "Rockwell Automation")
		Corporation.create(:name => "Northern Trust Corp.")
		Corporation.create(:name => "Timken")
		Corporation.create(:name => "Perini")
		Corporation.create(:name => "DaVita")
		Corporation.create(:name => "Expeditors International of Washington")
		Corporation.create(:name => "SunGard Data Systems")
		Corporation.create(:name => "CH2M Hill")
		Corporation.create(:name => "Kelly Services")
		Corporation.create(:name => "BJ Services")
		Corporation.create(:name => "Graybar Electric")
		Corporation.create(:name => "Charles Schwab")
		Corporation.create(:name => "Western & Southern Financial Group")
		Corporation.create(:name => "Jarden")
		Corporation.create(:name => "El Paso")
		Corporation.create(:name => "Gilead Sciences")
		Corporation.create(:name => "Scana")
		Corporation.create(:name => "NCR")
		Corporation.create(:name => "Harris")
		Corporation.create(:name => "Allegheny Technologies", :logo_path => "AlleghenyTechologies.png")
		Corporation.create(:name => "Host Hotels & Resorts")
		Corporation.create(:name => "Blockbuster")
		Corporation.create(:name => "Western Union")
		Corporation.create(:name => "Clorox")
		Corporation.create(:name => "BorgWarner")
		Corporation.create(:name => "Foot Locker")
		Corporation.create(:name => "Barnes & Noble")
		Corporation.create(:name => "Unisys")
		Corporation.create(:name => "Freescale Semiconductor")
		Corporation.create(:name => "AECOM Technology", :logo_path => "AECOM.png")
		Corporation.create(:name => "Spectra Energy")
		Corporation.create(:name => "FMC Technologies")
		Corporation.create(:name => "Advance Auto Parts", :logo_path => "AdvanceAutoParts.png")
		Corporation.create(:name => "Mylan")
		Corporation.create(:name => "Hershey")
		Corporation.create(:name => "CB Richard Ellis Group")
		Corporation.create(:name => "Telephone & Data Systems")
		Corporation.create(:name => "Icahn Enterprises")
		Corporation.create(:name => "Universal Health Services")
		Corporation.create(:name => "PetSmart")
		Corporation.create(:name => "BlackRock")
		Corporation.create(:name => "Con-way")
		Corporation.create(:name => "Lubrizol")
		Corporation.create(:name => "CVR Energy")
		Corporation.create(:name => "MDU Resources Group")
		Corporation.create(:name => "MasterCard")
		Corporation.create(:name => "United Stationers")
		Corporation.create(:name => "Auto-Owners Insurance")
		Corporation.create(:name => "NYSE Euronext")
		Corporation.create(:name => "PepsiAmericas")
		Corporation.create(:name => "Crosstex Energy")
		Corporation.create(:name => "Manitowoc")
		Corporation.create(:name => "Polo Ralph Lauren")
		Corporation.create(:name => "Fiserv")
		Corporation.create(:name => "Sealed Air")
		Corporation.create(:name => "Insight Enterprises")
		Corporation.create(:name => "NuStar Energy")
		Corporation.create(:name => "Asbury Automotive Group")
		Corporation.create(:name => "Molson Coors Brewing")
		Corporation.create(:name => "Rockwell Collins")
		Corporation.create(:name => "Realogy")
		Corporation.create(:name => "W.R. Berkley")
		Corporation.create(:name => "Brunswick")
		Corporation.create(:name => "Nash-Finch")
		Corporation.create(:name => "Leggett & Platt")
		Corporation.create(:name => "Universal American")
		Corporation.create(:name => "Broadcom")
		Corporation.create(:name => "Brightpoint")
		Corporation.create(:name => "Consol Energy")
		Corporation.create(:name => "Big Lots")
		Corporation.create(:name => "Dollar Tree")
		Corporation.create(:name => "Legg Mason")
	end

  def self.down
	  Corporation.delete_all
  end
end
