class CreateStateAgeLookups < ActiveRecord::Migration
  def self.up
    create_table :state_age_lookups do |t|
      t.integer :state_id
      t.integer :age_1
      t.integer :age_2
      t.integer :age_3
      t.integer :age_4
      t.integer :age_5
      t.integer :age_6
      t.integer :age_7
      t.integer :age_8
      t.integer :age_9
      t.integer :age_10
      t.integer :age_11
      t.integer :age_12
      t.integer :age_13
      t.integer :age_14
      t.integer :age_15
      t.integer :age_16
      t.integer :age_17
      t.integer :age_18
      t.integer :age_19
      t.integer :age_20
      t.integer :age_21
      t.integer :age_22
      t.integer :age_23
      t.integer :age_24
      t.integer :age_25
      t.integer :age_26
      t.integer :age_27
      t.integer :age_28
      t.integer :age_29
      t.integer :age_30
      t.integer :age_31
      t.integer :age_32
      t.integer :age_33
      t.integer :age_34
      t.integer :age_35
      t.integer :age_36
      t.integer :age_37
      t.integer :age_38
      t.integer :age_39
      t.integer :age_40
      t.integer :age_41
      t.integer :age_42
      t.integer :age_43
      t.integer :age_44
      t.integer :age_45
      t.integer :age_46
      t.integer :age_47
      t.integer :age_48
      t.integer :age_49
      t.integer :age_50
      t.integer :age_51
      t.integer :age_52
      t.integer :age_53
      t.integer :age_54
      t.integer :age_55
      t.integer :age_56
      t.integer :age_57
      t.integer :age_58
      t.integer :age_59
      t.integer :age_60
      t.integer :age_61
      t.integer :age_62
      t.integer :age_63
      t.integer :age_64
      t.integer :age_65
      t.integer :age_66
      t.integer :age_67
      t.integer :age_68
      t.integer :age_69
      t.integer :age_70
      t.integer :age_71
      t.integer :age_72
      t.integer :age_73
      t.integer :age_74
      t.integer :age_75
      t.integer :age_76
      t.integer :age_77
      t.integer :age_78
      t.integer :age_79
      t.integer :age_80
      t.integer :age_81
      t.integer :age_82
      t.integer :age_83
      t.integer :age_84
      t.integer :age_85
      t.integer :age_86
      t.integer :age_87
      t.integer :age_88
      t.integer :age_89
      t.integer :age_90
      t.integer :age_91
      t.integer :age_92
      t.integer :age_93
      t.integer :age_94
      t.integer :age_95
      t.integer :age_96
      t.integer :age_97
      t.integer :age_98
      t.integer :age_99
      t.integer :age_100
    end
  end

  def self.down
    drop_table :state_age_lookups
  end
end
